### PR TITLE
[fix] fransinette strict mode except TLE

### LINKED ISSUE #5: this code will not pass francinette strict mode.
Hi I am yliu.
I have found your code will pass the normal mode of
the following tester, however not with --strict option enabled.

https://github.com/xicodomingues/francinette/tree/master

### PR DESCRIPTION
**Pull request by alex216**
This commit should pass -strict mode except long txt(It will TLE.)
Also, norminette is not applied purposely, so that it's easier to revise.

### CODE REVIEW

File: get_next_line_bonus.c [hunk 1]
```diff
@@ -50,17 +61,23 @@ char	*get_next_line(int fd)
...
 	if (!end_ptr)
 		return (NULL);
-	line = ft_strndup(save[fd], end_ptr - save[fd]);
+	line = gnl_strndup(save[fd], end_ptr - save[fd]);
+	if (!line)
+	{
+		free(save[fd]);
+		save[fd] = NULL;
+		return (NULL);
+	}
```
Comment (rask24) [inline get_next_line_bonus.c:73]: 👍🏼

File: get_next_line_bonus.c [hunk 2]
```diff
@@ -20,15 +20,24 @@ static char	*append_to_save(char **save, int fd)
...
 			break ;
 		buffer[read_size] = '\0';
-		*save = ft_strjoin_with_free(*save, buffer, 0b10);
-		nl_ptr = ft_strchr(*save, '\n');
+		*save = gnl_strjoin_with_free(save, &buffer, 0b10);
+		if (!*save)
+		{
+			free(buffer);
+			return (NULL);
+		}
```
Comment (rask24) [inline get_next_line_bonus.c]: I think this if statement is unnecessary.
It seems necessary for performance improvement, but whether this if statement exists or not, the TLE issue will not be resolved. It would be better to remove it for issue#5 and norm.

File: get_next_line_bonus.c [hunk 3]
```diff
@@ -37,7 +46,9 @@ static char	*append_to_save(char **save, int fd)
 	}
 	free(buffer);
 	if (read_size == 0 && *save)
-		return (ft_strchr(*save, '\0'));
+		return (gnl_strchr(*save, '\0'));
+	free(*save);
+	*save = NULL;
```
Comment (rask24) [inline get_next_line_bonus.c:40]: 👍🏼

File: get_next_line.c [hunk 4]
```diff
@@ -20,15 +20,24 @@ static char	*append_to_save(char **save, int fd)
...
 		buffer[read_size] = '\0';
-		*save = ft_strjoin_with_free(*save, buffer, 0b10);
-		nl_ptr = ft_strchr(*save, '\n');
+		*save = gnl_strjoin_with_free(save, &buffer, 0b10);
+		if (!*save)
+		{
+			free(buffer);
+			return (NULL);
+		}
+		nl_ptr = gnl_strchr(*save, '\n');
```
Comment (rask24) [inline get_next_line.c:29]: I think this if statement is unnecessary.
It seems necessary for performance improvement, but whether this if statement exists or not, the TLE issue will not be resolved. It would be better to remove it for issue#5 and norm.

File: get_next_line.c [hunk 5]
```diff
@@ -50,17 +61,23 @@ char	*get_next_line(int fd)
...
 	if (!end_ptr)
 		return (NULL);
-	line = ft_strndup(save[fd], end_ptr - save[fd]);
+	line = gnl_strndup(save[fd], end_ptr - save[fd]);
+	if (!line)
+	{
+		free(save[fd]);
+		save[fd] = NULL;
+		return (NULL);
+	}
```
Comment (rask24) [inline get_next_line.c:73]: 👍🏼

File: get_next_line_bonus.c [hunk 6]
```diff
@@ -20,15 +20,24 @@ static char	*append_to_save(char **save, int fd)
 
 	buffer = malloc(BUFFER_SIZE + 1);
 	if (!buffer)
+	{
+		free(*save);
+		*save = NULL;
 		return (NULL);
+	}
```
Comment (rask24) [inline get_next_line_bonus.c]: 👍🏼

File: get_next_line_utils.c [hunk 7]
```diff
@@ -62,34 +62,48 @@ char	*ft_strndup(const char *s, size_t n)
...
+			free(*s1);
+			*s1 = NULL;
+		}
+		if (free_flag & 0b01)
+		{
+			free(*s2);
+			*s2 = NULL;
+		}
+		return (NULL);
+	}
```
Comment (rask24) [inline get_next_line_utils.c]: I think this if statement is not necessary. because `if (ret && *s1)` and `if (ret && *s2)` include NULL checking.

File: get_next_line_utils_bonus.c [hunk 8]
```diff
@@ -62,34 +62,48 @@ char	*ft_strndup(const char *s, size_t n)
...
+			free(*s1);
+			*s1 = NULL;
+		}
+		if (free_flag & 0b01)
+		{
+			free(*s2);
+			*s2 = NULL;
+		}
+		return (NULL);
+	}
```
Comment (rask24) [inline get_next_line_utils_bonus.c]: I think this if statement is not necessary. because `if (ret && *s1)` and `if (ret && *s2)` include NULL checking.

**Comment by rask24** [comment]
@alex216 
I have pushed the code with the modifications referring to your PR.
If there are any issues, please leave comments.

File: get_next_line_utils.c (hunk 7 above)
Comment (alex216) [reply get_next_line_utils.c]: Confirmed. You are right.

File: get_next_line_utils_bonus.c (hunk 8 above)
Comment (alex216) [reply get_next_line_utils_bonus.c]: Confirmed. You are right.

File: get_next_line_bonus.c (hunk 2 above)
Comment (alex216) [reply get_next_line_bonus.c]: Confirmed. You are right. It is an unneccessary if statement.

File: get_next_line.c (hunk 4 above)
Comment (alex216) [reply get_next_line.c:29]: Confirmed. You are right. It is an unneccessary if statement.

**Review by rask24 — APPROVED** [review]

**Comment by alex216** [comment]
@rask24 
👍
